<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateAnswersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('answers', function (Blueprint $table) {
            $table->id();

            $table->integer('sex')->nullable();
            $table->integer('age_')->nullable();
            $table->integer('age_c')->nullable();
            $table->integer('height')->nullable();
            $table->integer('height_c')->nullable();
            $table->integer('weight')->nullable();
            $table->integer('weight_c')->nullable();
            $table->integer('bmi')->nullable();
            $table->integer('hometown')->nullable();
            $table->integer('hometown_c')->nullable();
            $table->integer('address')->nullable();
            $table->integer('address_c')->nullable();
            $table->integer('job')->nullable();
            $table->integer('job_c')->nullable();
            $table->integer('family')->nullable();
            $table->integer('children')->nullable();
            $table->integer('children_c')->nullable();
            $table->integer('income')->nullable();
            $table->integer('income_c')->nullable();
            $table->integer('school')->nullable();
            $table->integer('activity')->nullable();
            $table->integer('when_interest')->nullable();
            $table->integer('activity_years')->nullable();
            $table->integer('hiding_years')->nullable();
            $table->integer('when_will_start')->nullable();
            $table->integer('hadatais')->nullable();
            $table->integer('gyocchi')->nullable();
            $table->integer('sasa')->nullable();
            $table->integer('goukaou_hadatai')->nullable();
            $table->integer('nukopan_hadatai')->nullable();
            $table->integer('other_hadatai')->nullable();
            $table->integer('masks')->nullable();
            $table->integer('masks_c')->nullable();
            $table->integer('sigma')->nullable();
            $table->integer('iruka')->nullable();
            $table->integer('zukokan')->nullable();
            $table->integer('nukopan_friend')->nullable();
            $table->integer('nukopan')->nullable();
            $table->integer('monaka')->nullable();
            $table->integer('ayame')->nullable();
            $table->integer('rins')->nullable();
            $table->integer('ami')->nullable();
            $table->integer('hyokkame')->nullable();
            $table->integer('munimuni')->nullable();
            $table->integer('goukaou')->nullable();
            $table->integer('raigeki')->nullable();
            $table->integer('other_domestic')->nullable();
            $table->integer('other_abroad')->nullable();
            $table->integer('handmade')->nullable();
            $table->integer('interest_trigger')->nullable();
            $table->integer('join_trigger')->nullable();
            $table->integer('alone_freq')->nullable();
            $table->integer('offkai_freq')->nullable();
            $table->integer('nomikai_freq')->nullable();
            $table->integer('very_closed_event_freq')->nullable();
            $table->integer('closed_event_freq')->nullable();
            $table->integer('opened_event_freq')->nullable();
            $table->integer('location_freq')->nullable();
            $table->integer('studio_freq')->nullable();
            $table->integer('expedition_freq')->nullable();
            $table->integer('creation_freq')->nullable();
            $table->integer('other_freq')->nullable();
            $table->integer('masks_outgo')->nullable();
            $table->integer('clothes_outgo')->nullable();
            $table->integer('transport_outgo')->nullable();
            $table->integer('communication_outgo')->nullable();
            $table->integer('event_outgo')->nullable();
            $table->integer('sum_outgo')->nullable();
            $table->integer('father_know')->nullable();
            $table->integer('mother_know')->nullable();
            $table->integer('brother_know')->nullable();
            $table->integer('closed_friend_know')->nullable();
            $table->integer('friend_know')->nullable();
            $table->integer('colleagure_know')->nullable();
            $table->integer('partner_know')->nullable();
            $table->integer('which_attractive')->nullable();
            $table->integer('gender')->nullable();
            $table->integer('sexual_orientation')->nullable();
            $table->integer('partners_same_sex')->nullable();
            $table->integer('partners_different_sex')->nullable();
            $table->integer('partners')->nullable();
            $table->integer('marriage_thought')->nullable();
            $table->integer('same_sex_kiss')->nullable();
            $table->integer('same_sex_sex')->nullable();
            $table->integer('different_sex_kiss_without_brothel')->nullable();
            $table->integer('different_sex_sex_without_brothel')->nullable();
            $table->integer('different_sex_kiss_in_brothel')->nullable();
            $table->integer('different_sex_sex_in_brothel')->nullable();
            $table->integer('is_virgin')->nullable();
            $table->integer('other_hobby')->nullable();
            $table->integer('spend_holiday')->nullable();
            $table->integer('official_show_thought')->nullable();
            $table->integer('cross_dress_thought')->nullable();
            $table->integer('kemono_thought')->nullable();
            $table->integer('want_other_let_wear')->nullable();
            $table->integer('kig_molding_score_high')->nullable();
            $table->integer('kig_molding_score_low')->nullable();
            $table->integer('my_body_score')->nullable();
            $table->integer('my_performance_score')->nullable();
            $table->integer('popularity_thought')->nullable();
            $table->integer('body_gap_thought')->nullable();
            $table->integer('kaburi_thought')->nullable();
            $table->integer('scare_thought')->nullable();
            $table->integer('get_popular_thought')->nullable();
            $table->integer('female_popular_thought')->nullable();
            $table->integer('doll_thought')->nullable();
            $table->integer('single_eye_thought')->nullable();
            $table->integer('hashimoto_thought')->nullable();
            $table->integer('proudness')->nullable();
            $table->integer('original_thought')->nullable();
            $table->integer('differnce_cosplay_thought')->nullable();
            $table->integer('sucos_thought')->nullable();
            $table->integer('retire_thought')->nullable();
            $table->integer('other_hobby_thought')->nullable();
            $table->integer('gap_thought')->nullable();
            $table->integer('greeting_shame')->nullable();
            $table->integer('citizenship_thought')->nullable();
            $table->integer('sexual_arousal')->nullable();
            $table->integer('sexual_arousal_c')->nullable();
            $table->integer('which_sex_want_wear')->nullable();
            $table->integer('tsf_pervision')->nullable();
            $table->integer('want_female_voice')->nullable();
            $table->integer('want_facial_expression')->nullable();
            $table->integer('lovey_with_male')->nullable();
            $table->integer('kiss_to_kig')->nullable();
            $table->integer('hand_job')->nullable();
            $table->integer('human_or_kig_expression')->nullable();
            $table->integer('girl_in_male20')->nullable();
            $table->integer('girl_in_female20')->nullable();
            $table->integer('girl_in_male40')->nullable();
            $table->integer('girl_in_female40')->nullable();
            $table->integer('boy_in_male20')->nullable();
            $table->integer('boy_in_female20')->nullable();
            $table->integer('boy_in_male40')->nullable();
            $table->integer('boy_in_female40')->nullable();
            $table->integer('without_hadatai_thought')->nullable();
            $table->integer('inside_doll')->nullable();
            $table->integer('zimoe_fap')->nullable();
            $table->integer('tamoe_fap')->nullable();
            $table->integer('my_photo_fap')->nullable();
            $table->integer('other_photo_fap')->nullable();
            $table->integer('novel_fap')->nullable();
            $table->integer('imagine_fap')->nullable();
            $table->integer('nizi_fap')->nullable();
            $table->integer('kemono_fap')->nullable();
            $table->integer('sanzi_fap')->nullable();
            $table->integer('sanzi_abnormal_fap')->nullable();
            $table->integer('other_kig_fap')->nullable();
            $table->integer('other_fap')->nullable();
            $table->integer('has_denma')->nullable();
            $table->integer('want_go_or_made_gone')->nullable();
            $table->integer('eye_seen')->nullable();
            $table->integer('breath_sound')->nullable();
            $table->integer('sweat')->nullable();
            $table->integer('wrinles')->nullable();
            $table->integer('self_moe')->nullable();
            $table->integer('gichi')->nullable();
            $table->integer('mokkori')->nullable();
            $table->integer('voice_seen')->nullable();
            $table->integer('sperma')->nullable();
            $table->integer('hotness')->nullable();
            $table->integer('made_hotness')->nullable();
            $table->integer('limit_breath')->nullable();
            $table->integer('made_limit_breath')->nullable();
            $table->integer('bind')->nullable();
            $table->integer('made_bind')->nullable();
            $table->integer('tsf')->nullable();
            $table->integer('female_mask')->nullable();
            $table->integer('sigma_c')->nullable();
            $table->integer('iruka_c')->nullable();
            $table->integer('zukokan_c')->nullable();
            $table->integer('nukopan_friend_c')->nullable();
            $table->integer('nukopan_c')->nullable();
            $table->integer('monaka_c')->nullable();
            $table->integer('ayame_c')->nullable();
            $table->integer('rins_c')->nullable();
            $table->integer('ami_c')->nullable();
            $table->integer('munimuni_c')->nullable();
            $table->integer('goukaou_c')->nullable();
            $table->integer('raigeki_c')->nullable();
            $table->integer('other_domestic_c')->nullable();
            $table->integer('other_abroad_c')->nullable();
            $table->integer('handmade_c')->nullable();
            $table->integer('gyocchi_c')->nullable();
            $table->integer('sasa_c')->nullable();
            $table->integer('goukaou_hadatai_c')->nullable();
            $table->integer('nukopan_hadatai_c')->nullable();
            $table->integer('other_hadatai_c')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('answers');
    }
}
